# Created with YamlCreate.ps1 v2.2.13 $debug=NVS0.CRLF.7-3-11.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Arixcel.ArixcelExplorer
PackageVersion: 8.6.8644
InstallerType: wix
Scope: user
InstallModes:
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /qn
  SilentWithProgress: /qb
UpgradeBehavior: install
Installers:
- Architecture: neutral
  InstallerUrl: https://www.arixcel.com/download/Arixcel_Explorer_v8.6.8644.msi
  InstallerSha256: D1990457EEADA70FDEDA5BB6FD128AF46DA13683C5E37331D4A61259A502FE8A
  ProductCode: '{2692BC83-3F5E-4D5D-AAA4-D4AAB1528F9E}'
ManifestType: installer
ManifestVersion: 1.5.0
